[package]
name = "typed-store-derive"
version = "0.3.0"
license = "Apache-2.0"
authors = ["Ade A. <ade@mystenlabs.com>"]
description = "macros for the typed-store crate"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.47"
quote = "1.0.23"
syn = { version = "1.0.104", features = ["full"] }


[dev-dependencies]
eyre = "0.6.8"
rocksdb = { version = "0.21", features = ["lz4", "multi-threaded-cf"], default-features = false }
tempfile = "3.4.0"
tokio = { version = "1", features = ["test-util"] }
typed-store = { path = "../typed-store" }
